### ISSUE TITLE
Deepsort import error?

### ISSUE THREAD

**Issue by Ivy-yang200** [ZJUFanLab/scDeepSort#22]
I got an error when importing deepsort. The existing solutions I've searched and found cannot solve this problem. What reason would it be?

Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:53)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import deepsort
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yangyuan/miniconda3/envs/scDeepsort/lib/python3.7/site-packages/deepsort/__init__.py"line 1, in <module>
    from .predict import DeepSortPredictor
  File "/home/yangyuan/miniconda3/envs/scDeepsort/lib/python3.7/site-packages/deepsort/predict.py",ine 1, in <module>
    import dgl
  File "/home/yangyuan/miniconda3/envs/scDeepsort/lib/python3.7/site-packages/dgl/__init__.py", lin8, in <module>
    from .backend import load_backend, backend_name
  File "/home/yangyuan/miniconda3/envs/scDeepsort/lib/python3.7/site-packages/dgl/backend/__init__.", line 74, in <module>
    load_backend(get_preferred_backend())
  File "/home/yangyuan/miniconda3/envs/scDeepsort/lib/python3.7/site-packages/dgl/backend/__init__.", line 23, in load_backend
    mod = importlib.import_module('.%s' % mod_name, __name__)
  File "/home/yangyuan/miniconda3/envs/scDeepsort/lib/python3.7/importlib/__init__.py", line 127, iimport_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/yangyuan/miniconda3/envs/scDeepsort/lib/python3.7/site-packages/dgl/backend/tensorflo__init__.py", line 4, in <module>
    from .tensor import *
  File "/home/yangyuan/miniconda3/envs/scDeepsort/lib/python3.7/site-packages/dgl/backend/tensorflotensor.py", line 31, in <module>
    import tfdlpack
  File "/home/yangyuan/miniconda3/envs/scDeepsort/lib/python3.7/site-packages/tfdlpack/__init__.py"line 2, in <module>
    from .core import __version__, to_dlpack, from_dlpack, get_device_and_dtype
  File "/home/yangyuan/miniconda3/envs/scDeepsort/lib/python3.7/site-packages/tfdlpack/core.py", li 15, in <module>
    dlpack_ops = load_library.load_op_library(libinfo.find_lib_path(libname)[0])
  File "/home/yangyuan/miniconda3/envs/scDeepsort/lib/python3.7/site-packages/tensorflow_core/pythoframework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/yangyuan/miniconda3/envs/scDeepsort/lipython3.7/site-packages/tfdlpack/libtfdlpack-tf-2.1.0.so: undefined symbol: _ZN10tensorflow12OpDefBlder4AttrESs

**Comment by Ivy-yang200** [comment]
I changed the environment and tried to install scdeepsort-cpu version. But another error occured. 

Python 3.8.10 (default, Jun 22 2022, 20:18:18)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
`>>> import deepso`
`2022-09-20 20:02:27.975542: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0`
`Traceback (most recent call last):
  File "/home/yangyuan/.local/lib/python3.8/site-packages/dgl/backend/tensorflow/tensor.py", line 31, in <module>
    import tfdlpack
ModuleNotFoundError: No module named 'tfdlpack'`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):`
  `File "<stdin>", line 1, in <module>`
 ` File "/home/yangyuan/.local/lib/python3.8/site-packages/deepsort/__init__.py", line 1, in <module>
    from .predict import DeepSortPredictor`
 ` File "/home/yangyuan/.local/lib/python3.8/site-packages/deepsort/predict.py", line 1, in <module>
    import dgl`
 ` File "/home/yangyuan/.local/lib/python3.8/site-packages/dgl/__init__.py", line 8, in <module>
    from .backend import load_backend, backend_name`
 ` File "/home/yangyuan/.local/lib/python3.8/site-packages/dgl/backend/__init__.py", line 74, in <module>
    load_backend(get_preferred_backend())`
 ` File "/home/yangyuan/.local/lib/python3.8/site-packages/dgl/backend/__init__.py", line 23, in load_backend
    mod = importlib.import_module('.%s' % mod_name, __name__)`
 ` File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)`
  `File "/home/yangyuan/.local/lib/python3.8/site-packages/dgl/backend/tensorflow/__init__.py", line 4, in <module>
    from .tensor import *`
  `File "/home/yangyuan/.local/lib/python3.8/site-packages/dgl/backend/tensorflow/tensor.py", line 33, in <module>
    raise ImportError('Cannot find tfdlpack, which is required by the Tensorflow backend. '`
`ImportError: Cannot find tfdlpack, which is required by the Tensorflow backend. Please follow https://github.com/VoVAllen/tf-dlpack for installation.`

What I'm confused about is that the author of tf-dlpack VoVAllen said that the project is no longer active and I cannot install it following the code.

**Comment by shaoxin0801** [comment]
You can try python 3.7.6. By the way, please set the default backend to "pytorch" for dgl.
